# -*- coding: utf-8 -*-
"""UTS ML_ALIF FIRMANSYAH_1227050016.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16GSrqd9z9wno8rPjxiC8J3Z-SwCGvPIK
"""

import pandas as pd

# Upload file CSV kamu di Google Colab dulu ya
from google.colab import files
uploaded = files.upload()

# Load dataset
df = pd.read_csv("dataset_buys_comp.csv")
df.head()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for column in df.columns:
    df[column] = le.fit_transform(df[column])

df.head()

X = df.drop("Buys_Computer", axis=1)
y = df["Buys_Computer"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))